# Generated by Django 4.2 on 2024-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
    ]
